"Usage: %s [options] [--] <dataset>\n"
"Select an optimal feature subset for Bayesian classification.\n"
"\n"
"Main options:\n"
"   -m, --mode=<string>          classification mode (binary|multiclass)\n"
"                                  [multiclass]\n"
"   -t, --truth=<string>         name of the label corresponding to the positive\n"
"                                  class, for binary classification\n"
"   -k, --folds=<integer>        number of folds for cross-validation [5]\n"
"   -S, --smooth=<float>         frequency increment for additive smoothing [0.5]\n"
"   -M, --measure=<string>       measure to maximize (accuracy|precision|recall|\n"
"                                  F1) [F1]\n"
"   -a, --average=<string>       averaging mode for multiclass classification\n"
"                                  (micro|macro) [macro]\n"
"   -s, --search=<string>        search mode (none|forward|forward-join|backward|\n"
"                                  backward-join) [forward-join]\n"
"   -F, --max-features=<integer> maximum number of features to select [inf]\n"
"   -L, --max-links=<integer>    maximum number of dependencies to model [inf]\n"
"\n"
"Output options:\n"
"   -v, --verbose                output performance measures for all evaluated\n"
"                                  models\n"
"   -c, --compact                output compressed JSON documents that fit on a\n"
"                                  single line\n"
"\n"
"General options:\n"
"   -h, --help                   display this message\n"
"   --version                    display the current version\n"
