"Usage: %s [options] <dataset>\n"
"Select an optimal feature subset for Bayesian classification.\n"
"\n"
"Main options:\n"
"   --mode=<binary|multiclass> classification mode [multiclass]\n"
"   --truth=<label_name>       name of the label corresponding to the positive\n"
"                                class, when doing binary classification\n"
"   --folds=<integer>          number of folds for cross-validation [5]\n"
"   --smooth=<float>           frequency increment for additive smoothing [0.5]\n"
"   --measure=<name>           measure to maximize (accuracy|precision|recall|F1)\n"
"                                [F1]\n"
"   --average=<micro|macro>    averaging mode for multiclass classification\n"
"                                 [macro].\n"
"   --search=<mode>            search mode (none|forward|forward-join|backward|\n"
"                                backward-join) [forward-join]\n"
"   --max-features=<integer>   maximum number of features to select [inf]\n"
"   --max-links=<integer>      maximum number of dependencies to model [inf]\n"
"\n"
"Output options:\n"
"   -v | --verbose             output performance measures for all evaluated\n"
"                                models\n"
"   --compact                  output compressed JSON documents that fit on a\n"
"                                single line\n"
"\n"
"General options:\n"
"   -h | --help                display this message\n"
"   --version                  display the current version\n"
